# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task1_Sample_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  
  # Pods for Task1_Sample_Project
   pod 'Alamofire', '~> 5.4' 
end
